//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelAdvance.PreviewHandlerPack.PreviewHandlers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HighlightResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HighlightResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FuelAdvance.PreviewHandlerPack.PreviewHandlers.Resources.HighlightResources", typeof(HighlightResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;definitions&gt;
        ///	&lt;definition name=&quot;C#&quot; caseSensitive=&quot;true&quot;&gt;
        ///		&lt;default&gt;
        ///			&lt;font name=&quot;Courier New&quot; size=&quot;11&quot; style=&quot;regular&quot; foreColor=&quot;black&quot; backColor=&quot;transparent&quot;/&gt;
        ///		&lt;/default&gt;
        ///		&lt;pattern name=&quot;Keyword&quot; type=&quot;word&quot;&gt;
        ///			&lt;font name=&quot;Courier New&quot; size=&quot;11&quot; style=&quot;regular&quot; foreColor=&quot;blue&quot; backColor=&quot;transparent&quot;/&gt;
        ///			&lt;word&gt;as&lt;/word&gt;
        ///			&lt;word&gt;is&lt;/word&gt;
        ///			&lt;word&gt;new&lt;/word&gt;
        ///			&lt;word&gt;sizeof&lt;/word&gt;
        ///			&lt;word&gt;typeof&lt;/word&gt;
        ///			&lt;word&gt;true&lt;/word&gt;
        ///			&lt;word&gt;false&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Definitions {
            get {
                return ResourceManager.GetString("Definitions", resourceCulture);
            }
        }
    }
}
